version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:14"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
